name: Marce05
on:
  push:
   branches:
     - main
     - ASt
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Checkmarx AST CLI Action
       uses: Checkmarx/ast-github-action@2.0.3
       with:
         project_name: ${{ github.repository }}
         cx_tenant: nfr_trustdimension
         base_uri: https://ast.checkmarx.net
         cx_client_id: ${{ secrets.CX_MARCE05 }}
         cx_client_secret: ${{ secrets.CX_MARCE05_SECRET }}
         branch: ${{ github.ref }}
